ROKT/rokt-demo-android

- app/build.gradle
- app/src/main/java/com/rokt/roktdemo/model/DemoLibrary.kt
- app/src/main/java/com/rokt/roktdemo/ui/NavGraph.kt
- app/src/main/java/com/rokt/roktdemo/ui/RoktDemoApp.kt
- app/src/main/java/com/rokt/roktdemo/ui/common/Spacer.kt
- app/src/main/java/com/rokt/roktdemo/ui/common/Text.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/DemeNavGraph.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/DemoHome.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/DemoPage.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/DemoViewModel.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/DestinationType.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/summary/SummaryDisclaimer.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/summary/SummaryPage.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/summary/SummaryViewModel.kt
- app/src/main/res/values/strings.xml
- buildSrc/src/main/java/dependencies.kt
> Feature walkthrough summary disclaimer

- app/src/main/java/com/rokt/roktdemo/data/Result.kt
- app/src/main/java/com/rokt/roktdemo/data/library/DemoLibraryRepositoryMockImpl.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/DemoPage.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/DemoViewModel.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/custom/screen/account/AccountDetailsScreen.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/custom/screen/customer/CustomerDetailsScreen.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/error/GeneralError.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/walkthrough/WalkthroughPage.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/walkthrough/screen/WalkthroughScreen.kt
- app/src/main/res/values/strings.xml
> Network Error Page

- app/src/main/java/com/rokt/roktdemo/ui/demo/DemoPage.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/DemoViewModel.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/custom/CustomCheckoutPage.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/custom/CustomCheckoutViewModel.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/custom/screen/account/AccountDetailsScreen.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/custom/screen/account/AccountDetailsViewModel.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/custom/screen/customer/CustomerDetailsScreen.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/custom/screen/customer/CustomerDetailsViewModel.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/summary/SummaryViewModel.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/walkthrough/WalkthroughPage.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/walkthrough/WalkthroughViewModel.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/walkthrough/screen/WalkthroughScreen.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/walkthrough/screen/WalkthroughScreenViewModel.kt
- app/src/test/java/com/rokt/roktdemo/WalkthroughScreenViewModelTest.kt
- app/src/test/java/com/rokt/roktdemo/WalkthroughViewModelTest.kt
- app/src/test/java/com/rokt/roktdemo/checkout/AccountDetailsViewModelTest.kt
- app/src/test/java/com/rokt/roktdemo/checkout/CustomCheckoutViewModelTest.kt
- app/src/test/java/com/rokt/roktdemo/checkout/CustomerDetailsViewmodelTest.kt
Refactored to match IOS. The demolibrary is fetched once in "DemoPage" then passed down to all children
> Refactor to pass the Demolibrary to children

- app/src/main/java/com/rokt/roktdemo/ui/demo/custom/screen/customer/CustomerDetailsViewModel.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/walkthrough/screen/WalkthroughScreenViewModel.kt
- app/src/main/res/values/strings.xml
- buildSrc/src/main/java/dependencies.kt
- gradle/wrapper/gradle-wrapper.properties
The email received from the back-end will be randomized
> randomise email

- app/build.gradle
- app/src/main/java/com/rokt/roktdemo/ui/demo/summary/SummaryDisclaimer.kt
- app/src/main/res/values/strings.xml
> update ui and buttons

- app/src/main/java/com/rokt/roktdemo/ui/about/AboutPage.kt
- app/src/main/java/com/rokt/roktdemo/ui/home/HomePage.kt
- app/src/main/res/values-night/themes.xml
> dark mode issues fixed

- app/build.gradle
- app/src/main/java/com/rokt/roktdemo/ui/common/Text.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/DemoHome.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/DestinationType.kt
- app/src/main/java/com/rokt/roktdemo/ui/demo/summary/SummaryPage.kt
- app/src/main/res/values/strings.xml
> adjust line spacing

- .github/CODEOWNERS
- .github/pull_request_template.md
> add GitHub Configs

- app/build.gradle
- buildSrc/src/main/java/dependencies.kt
Updated Sdk version and increment Version code
[(https://rokt.atlassian.net/browse/MP-1566)
> updated Rokt sdk to 3.7.0 and increment verion code and name

- app/build.gradle
- buildSrc/src/main/java/dependencies.kt
- changed rokt sdk version
- Incemented app version code
> EINT-106 increment rokt sdk version, and app versioncode

- app/build.gradle
- app/src/main/java/com/rokt/roktdemo/utils/Extensions.kt
- buildSrc/src/main/java/dependencies.kt
> updated to rokt sdk 3.8.0

- app/build.gradle
- build.gradle
- buildSrc/build.gradle.kts
- buildSrc/src/main/java/dependencies.kt
- Updated Rokt Sdk to 3.10.0
- Removed JCenter instances
> updated rokt sdk to 3.10.0

- app/build.gradle
- buildSrc/src/main/java/dependencies.kt
Updating sdk version to 3.12.0.
Updated rokt sdk version to 3.12.0
Updated app version to 1.2.3
Verified demo app works with new sdk version
> [MP-2016] Update sdk version to 3.12.0

- app/build.gradle
- app/src/test/java/com/rokt/roktdemo/checkout/AccountDetailsViewModelTest.kt
- app/src/test/java/com/rokt/roktdemo/checkout/CustomerDetailsViewmodelTest.kt
- buildSrc/src/main/java/dependencies.kt
Provide a summary of why you are making this pull request and the issue it is fixing. Also include relevant motivation and context that a reviewer should know. List any dependencies that are required for this change.
Fixes [([issue](https://rokt.atlassian.net/browse/MP-2231))]
> MP-2231 Update Rokt SDK version to 3.14.0

- app/build.gradle
- buildSrc/src/main/java/dependencies.kt
Provide a summary of why you are making this pull request and the issue it is fixing. Also include relevant motivation and context that a reviewer should know. List any dependencies that are required for this change.
> MP2231 update SDK version to 3.14.1

- .buildkite/pipeline.yml
- app/build.gradle
- app/src/debug/AndroidManifest.xml
- app/src/debug/res/xml/network_security_config.xml
- app/src/main/AndroidManifest.xml
- build.gradle
- buildSrc/build.gradle.kts
- buildSrc/gradle/wrapper/gradle-wrapper.properties
- buildSrc/src/main/java/dependencies.kt
- docker-compose.yml
- gradle/wrapper/gradle-wrapper.properties
Use RoktSDK 4.0.0-alpha.1 with DCUI support
Fixes [MP-2384](https://rokt.atlassian.net/browse/MP-2384)
Network debug settings
Essential version updates
Tested locally
> MP-2384 - Version update - use DCUI 4.0.0 and make compatible

- app/build.gradle
- buildSrc/src/main/java/dependencies.kt
Update Rokt SDK version to `3.15.4`
Fixes [MP-2575](https://rokt.atlassian.net/browse/MP-2575)
SDK version change
Tested locally
> MP-2575 - Update Rokt SDK version to 3.15.4

- app/build.gradle
- buildSrc/src/main/java/dependencies.kt
Update the SDK version
Fixes [MP-2667](https://rokt.atlassian.net/browse/MP-2667)
Version update
> MP-2667 - Update Rokt SDK version to `3.15.5`

- buildSrc/src/main/java/dependencies.kt
SDK version change
Fixes [MP-2651](https://rokt.atlassian.net/browse/MP-2651)
Version update
> MP-2651 - Update Rokt SDK version to 4.0.0-beta.1

- buildSrc/src/main/java/dependencies.kt
Update Rokt SDK version to 4.0.0-beta.2
Version update
> MP-2651 - Update Rokt SDK version to 4.0.0-beta.2

- .buildkite/bin/create_tag.sh
- .buildkite/bin/update_versions.sh
- .buildkite/release.pipeline.yml
- .gitignore
- README.md
Cherry-picked commit from 1.1.x branch and updated some things.
Fixes [MP-2726](https://rokt.atlassian.net/browse/MP-2726)
- Added release pipeline from 1.1.x
- Updated script for different app/build.gradle file
- Changed pipeline to use DCUI app name
Ran updated script locally
> [MP-2725] Automated pipeline DCUI App

- build.gradle
Change the Rokt SDK maven repo url
Fixes [MP-3084](https://rokt.atlassian.net/browse/MP-3084)
Changing the maven configuration
Tested locally
> MP-3084 - Update maven repo url

- app/src/main/java/com/rokt/roktdemo/ui/layouts/DemoLayoutsPage.kt
Preview page isn't scrollable so embedded layouts can't always be viewed in their entirety.
Fixes [NO-JIRA]
- Made the button and layout area scrollable
- Previewed embedded and could scroll
> [NO-JIRA] Add Scroll for Embedded Previews

- app/build.gradle
- app/proguard-rules.pro
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/rokt/roktdemo/ui/about/AboutPage.kt
- app/src/main/res/xml/network_security_config.xml
- buildSrc/src/main/java/dependencies.kt
App was crashing from AboutPage when trying to load the network image using coil.
* Updated coil library version and use official `AsyncImage` instead of `accompanist`.
* Updated the proguard rules to fix the QR code scanning issues
* Add network_security_config.xml so that calls can be inspected with user installed certificates
Fixes [MP-3365](https://rokt.atlassian.net/browse/MP-3365)
Bugfix in AboutPage
Tested locally
> MP-3365 - Fix app crash from About page

- app/src/main/java/com/rokt/roktdemo/ui/layouts/ScanQrViewModel.kt
This PR is to include the `versionId` to the attributes in the request payload.
- Added `versionId` to the attributes
> CNC-1659: Add versionId to the attributes in the request payload

- .cortex/catalog/rokt-demo-android.yaml
Adding cortex config to the repository
Adding cortex metadata
NA
> MP-3478 - Add cortex config

- app/build.gradle
- buildSrc/src/main/java/dependencies.kt
This PR is to update the coil library version to 2.2.0
Fixes [(No_Jira)]
> No jira update coil version

- app/src/main/java/com/rokt/roktdemo/ui/layouts/DemoLayoutsPage.kt
- app/src/main/java/com/rokt/roktdemo/ui/layouts/ScanQrViewModel.kt
- app/src/main/java/com/rokt/roktdemo/ui/layouts/model/DemoModeConfig.kt
- app/src/main/java/com/rokt/roktdemo/ui/layouts/model/PreviewData.kt
- buildSrc/src/main/java/dependencies.kt
- gradle.properties
* Extract new `language` and `layoutVariantIds` properties from the QR code data
* Construct the `demoConfig` parameter
* Send `demoConfig` and `language` as attribute
* Disable the refresh button
Fixes [LAYOUT-1026](https://rokt.atlassian.net/browse/LAYOUT-1026)
Support new QR code preview format
Tested locally using Prod iOS templates
https://github.com/user-attachments/assets/3a29a4ef-1181-4e4b-a7d8-15600efd42dc
https://github.com/user-attachments/assets/a5f674a1-7b12-4d19-b1e9-330d87e9e4da
> LAYOUT-1026 - Update Demo App to support new attribute demoConfig

- app/src/main/java/com/rokt/roktdemo/ui/layouts/ScanQrViewModel.kt
Remove unused attribute from demo experiences request
> LAYOUT-1026 - Remove unused attribute from demo experiences request

- .cortex/catalog/rokt-demo-android.yaml
This JIRA is to update cortex team owners.
Fixes [(No_Jira)]
> cortex team owner update

- app/src/main/java/com/rokt/roktdemo/ui/layouts/DemoLayoutsPage.kt
- buildSrc/src/main/java/dependencies.kt
> NoJira - Fix PlainTooltipBox not available in material3

- .gitignore
- app/build.gradle
- build.gradle
- buildSrc/src/main/java/dependencies.kt
Adding the basic Firebase plugins to the app to allow for further development in the target workstation branch.
Fixes [NI-514](https://rokt.atlassian.net/browse/NI-514)
Added Firebase plugins
Gradle sync and built the app locally
> NI-514 Add Firebase Plugins

- .github/workflows/distribute-to-firebase.yml
- app/build.gradle
- build.gradle
- buildSrc/src/main/java/dependencies.kt
This adds the required authentication and step to publish the app to Firebase. It is not fully configured yet re testing groups etc., but this adds the steps required to actually upload it to Firebase. 
Fixes [NI-555](https://rokt.atlassian.net/browse/NI-555)
- Removed the Gradle Plugin as it was not working with Auth
- Added step to Auth via WIF + GH Actions OIDC
- Added Firebase CLI
- Added step to distribute via the CLI
https://github.com/ROKT/rokt-demo-android/actions/runs/13300419319
Still some cleanup to come
> NI-555 Add Firebase Distribution Step

- .github/workflows/distribute-to-firebase.yml
Adding automated distribution to tester groups
Fixes [NI-515](https://rokt.atlassian.net/browse/NI-515)
Add distribution groups to distribution step
Run workflow and got the release email
> NI-515 Add Tester Distribution

- .github/workflows/distribute-to-firebase.yml
- .gitignore
- app/build.gradle
- build.gradle
- buildSrc/src/main/java/dependencies.kt
Merging workstation into main
Fixes [NI-476](https://rokt.atlassian.net/browse/NI-476)
- Add plugins
- Add workflow
- Add auth and distribution with Firebase
Successful workflow publish
> NI-476 Set up Firebase for Distribution

- .cortex/catalog/rokt-demo-android.yaml
- .github/CODEOWNERS
- README.md
Update CODEOWNERS and cortex configuration to reflect the new team structure
> NoJira - Update ownership and team

- .github/actions/build-apk/action.yml
- .github/actions/setup-java/action.yml
- .github/actions/upload-apk/action.yml
- .github/workflows/release-from-main.yml
- .github/workflows/trigger-release-to-firebase.yml
- .github/workflows/trigger-snapshot-to-firebase.yml
- gradle.properties
Create github actions workflow for publishing the demo app to Firebase app distribute
Fixes [SQDSDKS-7364](https://mparticle-eng.atlassian.net/browse/SQDSDKS-7364)
Publish workflow for Snapshot and Release builds
When the SDK is released in the `sdk-android-source` repo, it will trigger the workflow here.
- Get the version from the trigger and update the SDK version
- Align the app version with the SDK version.
- In case of snapshot, build and push the SDK to firebase snapshot testing group
- In case of release, create a PR and wait for it to get merged and publish the apk to firebase
> SQDSDKS-7364 - Add demo app publishing workflow

- .github/workflows/release-from-main.yml
Fix the error
`Warning: No files were found with the provided path: app-release.apk. No artifacts will be uploaded.`
> SQDSDKS-7364 - fix the APK artifact path

- .github/workflows/release-from-main.yml
Add write permission so that the workflow can create a release
Fix the workflow permission 
> SQDSDKS-7364 - fix the permission issue when creating release

- app/build.gradle
- build.gradle
- settings.gradle
For ease of development this PR adds Maven local to the list of resolvable repos
> chore: Add Maven local to repos
